version: '3.8'

services:

  lib:
    image: castor/context:dev
    build:
      context: .castor/docker
      dockerfile: ./lib/Dockerfile
      target: dev
      args:
        COMPOSER_USER: ${SPACE_USER:?}
        COMPOSER_TOKEN: ${SPACE_TOKEN:?}
    container_name: castor.context.lib
    working_dir: /castor/lib
    volumes:
      - .:/castor/lib
    user: castor
